services:
  server:
    build: 
      context: ./valefor-server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      #use a different env here so that npx migrate will still work locally
      - ./valefor-server/.env.prod
    environment: 
      - NODE_ENV=development
    volumes:
      - ./valefor-server/src:/app/src
  client:
    build:
      context: ./valefor-client
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - ./valefor-client/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./valefor-client/src:/app/src
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=valefor
      - POSTGRES_PASSWORD=valefor
      - POSTGRES_DB=valefor
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

